<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Maruthi" failures="1" tests="3" name="RetryTestExample" time="0.073" errors="0" timestamp="2025-08-21T10:01:09 IST">
  <testcase classname="TestNg_Day3.RetryTest" name="testRetryExample" time="0.015">
    <skipped/>
  </testcase> <!-- testRetryExample -->
  <testcase classname="TestNg_Day3.RetryTest" name="testRetryExample" time="0.002">
    <skipped/>
  </testcase> <!-- testRetryExample -->
  <testcase classname="TestNg_Day3.RetryTest" name="testRetryExample" time="0.002">
    <failure type="java.lang.AssertionError" message="Failing test to check retry logic">
      <![CDATA[java.lang.AssertionError: Failing test to check retry logic
at TestNg_Day3.RetryTest.testRetryExample(RetryTest.java:11)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testRetryExample -->
</testsuite> <!-- RetryTestExample -->
